version: "3.8"

services:
  app:
    container_name: lignumsoftPizza
    image: lignumsoftpizza
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    env_file: docker.env
    environment:
      - REACT_APP_BACKEND_HOST${REACT_APP_BACKEND_HOST}
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT